name: Update RSS feed

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 * * * *'
  push:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run execute.py
      run: |
        python execute.py ${{ secrets.EMAIL }}
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "ci: Automated update $(date)" -a | exit 0
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
